### PR TITLE
Add about dialog to Lychee-front

### PR DESCRIPTION
**Pull request by d7415**
Fixes #137

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
Yes, I think the About dialog should be in the language of the user.

**Comment by bennettscience** [comment]
Agreed, @LudovicRousseau.

**Comment by d7415** [comment]
Localisation done. Look ok to everyone? I have a commit for Lychee with the English.php changes ready for when I have a Lychee-front revision to pin it to.

**Comment by d7415** [comment]
Reminder to me: Fix issue ref when squashing.

**Comment by d7415** [comment]
Pushed the feature/about branch to Lychee if anyone wants to look (same caveat to me for merging)

**Comment by d7415** [comment]
Merged in 11a71a5

**Comment by d7415** [comment]
Added bonus: If/when the about dialog gets updated, we could potentially look at adding some localisation to the website :)

**Pull request closed without merging**
