### PR TITLE
allow download of small & medium files

### PR DESCRIPTION
**Pull request by guzzisti**
Extend frontend to correspond to LycheeOrg/Lychee#216, implements LycheeOrg/Lychee#204

This adds 2 additional entries in the context menu of a photo. The entries only show up if medium and/or small sizes are available.

### CODE REVIEW

**Comment by d7415** [comment]
I've only given this a quick look and a quick think - no detail or testing (yet, at least) but no objections here.

Laravel compatibility is a bit of a concern, but I'll leave that to @ildyria for now!

**Comment by ildyria** [comment]
@guzzisti for next time, you might want to create a new branch for your PR. It will allow you to keep a clean master branch where you can still modify things without polluting this PR. :smiley:

**Comment by guzzisti** [comment]
I understand your point, but there are no commits listed above that are not related to the topic of this PR.

**Comment by d7415** [comment]
> I understand your point, but there are no commits listed above that are not related to the topic of this PR.

I was about to write that ;)

New branches for PRs are good practice, but I usually forget...

**Comment by ildyria** [comment]
I know, I'm just giving you a small tip for the future if you want to work on multiple feature at the same time. :)

**Comment by ildyria** [comment]
Okay, I did some modifications, I can't push them to your master branch because of name conflicting etc... That is one of the reason why I prefer when PR have an actual branch dedicated. So I'm closing this and opening a new PR with your branch.

**Pull request closed without merging**
