### PR TITLE
Add user and better structure to session json

### PR DESCRIPTION
**Pull request by nagmat84**
This are the front-end changes for https://github.com/LycheeOrg/Lychee/pull/1443.

### CODE REVIEW

**Review by ildyria — APPROVED** [review]
LGTM.

**Review by kamil4 — APPROVED** [review]

**Comment by nagmat84** [comment]
BTW, this is not ready for merge if it is merged after https://github.com/LycheeOrg/Lychee/pull/1403 which I expect. In this case, this PR needs further adoptions, because the object `lychee.user` needs to be updated after user-updating requests. https://github.com/LycheeOrg/Lychee/pull/1403 introduces a change in how users are updated which this PR is not prepared for.

**Comment by nagmat84** [comment]
After https://github.com/LycheeOrg/Lychee/pull/1403 has been merged into the backend, this PR needed to adopt. So I think it should be re-reviewed. The following aspects have been changed (or actually added):

* `settings.createLogin` updates `lychee.user`
* `settings.changeLogin` updates `lychee.user`

This has been necessary, because https://github.com/LycheeOrg/Lychee/pull/1403 now updates the session of the backend after a user has been changed, and I want to keep the frontend synced. Technically, this is not necessary _now_, because there is currently no code which relies on condition that the backend and frontend user are the same, but I want to avoid future surprises.

**Review by kamil4 — APPROVED** [review]

**Review by ildyria — COMMENTED** [review]
LGTM.

Untested.

**Comment by ildyria** [comment]
I was looking at the return on `Session::init()`:
```
rights: {is_admin: true, is_locked: false, may_upload: true}
user: {id: 0, username: "admin", email: "test@test.com", may_upload: true, is_locked: false}
```
I am wondering if we want this duplication of _rights_, or if we just don't care in this specific case. :)

I would say that the serialization in `toArray()` is needed because of the user administration page.

**Pull request merged**
