### PR TITLE
Fix untranslatable strings

### PR DESCRIPTION
**Pull request by qwerty287**
Frontend part of https://github.com/LycheeOrg/Lychee/pull/1270

### CODE REVIEW

**Comment by ildyria** [comment]
While the intent is welcome, I fear that this one is not going to be merge, the reason being that #282 may revert some of those change.

I think a better approach would actually to make the PR on the [consistent_json_api](https://github.com/LycheeOrg/Lychee-front/tree/consistent_json_api) branch which will be merged. This is a way more future proof approach :)

**Comment by ildyria** [comment]
Note that for https://github.com/LycheeOrg/Lychee/pull/1271/files it does not matter because those are not impacted by the big json refactoring.

**Comment by qwerty287** [comment]
> I think a better approach would actually to make the PR on the consistent_json_api branch which will be merged. This is a way more future proof approach :)

So, I should close this and "recreate" it once #282 is merged?

**Comment by ildyria** [comment]
yes, you can either wait or use [consistent_json_api](https://github.com/LycheeOrg/Lychee-front/tree/consistent_json_api) as a base and make PR to that branch instead of master. :)

**Comment by qwerty287** [comment]
I'll close this and do it once again when #282 is finished.

**Pull request closed without merging**
