### PR TITLE
Hide passwords in users view

### PR DESCRIPTION
**Pull request by kamil4**
Also add hover explanations for the icons/checkboxes.

Finally, tweak the layout so that columns align nicely.

### CODE REVIEW

**Comment by ildyria** [comment]
I disagree with putting the password field as a password as we don't ask for confirmation (to prevent mistake when typing).

**Comment by kamil4** [comment]
Interesting point. But the UI is inconsistent about it then. Passwords used for album protection or, especially, the admin password (asked for on the first access to a fresh installation) are hidden.

**Comment by ildyria** [comment]
Then I would put the password for albums on "visible" and I would put a confirmation step for the password at a fresh installation. :)
Note that we don't ask for confirmation either for a new password when a user or the admin wants to change their password (should be the case).

In summary I would rather go for:
- Fresh installation and password change in settings: hidden with confirmation step (just another box bellow).
- User creation/modification, album password setting: visible.

Those should not need changes on the server side by the way. :)

**Comment by kamil4** [comment]
OK, my latest commit should address your feedback.

And it looks like server-side changes will be needed -- due to an added string in locales.

**Pull request merged**
