### PR TITLE
Public search functionality

### PR DESCRIPTION
**Pull request by copperschnack**
Hi Lychee-team,

as needed by us, and demanded in https://github.com/LycheeOrg/Lychee-Laravel/issues/49, we implemented a public search functionality in Lychee. Please feel free to review and maybe integrate it into your main branch.

As this feature comes with some changes to the backend, we will file a corresponding pull request there.

This is our first public pull request - so feedback is highly appreciated.

Thanks and regards

malte.

### CODE REVIEW

**Comment by bennettscience** [comment]
I was able to test and didn't see any problems. My only feedback would be that adding the search field in next to the "Hosted with Lychee" statement looks cramped. Perhaps we move the hosting credit to a footer?

**Comment by kamil4** [comment]
I like how comprehensive you were, including implementing a GUI for the settings. We typically just add a keyword under "Settings / More" -- which, I'll admit, is kind-of lazy and I think that we should bite the bullet and add GUI for all/most of the keywords there -- "one of these days"...

**Comment by copperschnack** [comment]
> I was able to test and didn't see any problems. My only feedback would be that adding the search field in next to the "Hosted with Lychee" statement looks cramped. Perhaps we move the hosting credit to a footer?

Thanks for your feedback. A footer has already been [brought up in screen design](https://gitter.im/LycheeOrg/Lobby?at=5ce25f5bad024978c6f8846a) by @SerenaButler - including the hosting credit. So, maybe we should wait on that.

Another option would be to make the text of the credit configurable. But that is a change, I did not want to introduce without consent with you guys, who do all this great work on Lychee...

**Comment by ildyria** [comment]
> Another option would be to make the text of the credit configurable. But that is a change, I did not want to introduce without consent by you guys, who do all this great work on Lychee...

There is already some work on that part, I still need to finish it.
https://github.com/LycheeOrg/Lychee/issues/5

**Comment by kamil4** [comment]
@ildyria I've got my changes ready for review but I can't push them to @copperschnack's master ("permission denied"). What should I do? Do I need to open a new PR or can we somehow retarget this one to a different repo?

**Comment by ildyria** [comment]
closed. See #101

**Pull request closed without merging**
